import { AssetListItem } from "./model";

export const enStocks: AssetListItem[] = [
  {
    id: "alphabet-class-a",
    logo: "alphabet-class-a.svg",
    name: "Google (Alphabet)",
    desc: "IT, Search",
  },
  {
    id: "apple",
    logo: "apple.svg",
    name: "Apple",
    desc: "IT, iPhone",
  },
  {
    id: "microsoft",
    logo: "microsoft.svg",
    name: "Microsoft",
    desc: "IT, ChatGPT",
  },
  {
    id: "adobe",
    logo: "adobe.svg",
    name: "Adobe",
    desc: "Contents Software",
  },
  {
    id: "johnson-and-johnson",
    logo: "johnson-and-johnson.svg",
    name: "Johnson & Johnson",
    desc: "Medical",
  },
  {
    id: "nike",
    logo: "nike.svg",
    name: "Nike",
    desc: "running shoes, sporting goods",
  },
  {
    id: "3m",
    logo: "3m.png",
    name: "3M",
    desc: "Science",
  },
  {
    id: "logitech",
    logo: "logitech.svg",
    name: "Logitech",
    desc: "PC peripherals",
  },
  {
    id: "mcdonalds",
    logo: "mcdonalds.svg",
    name: "Mcdonald's",
    desc: "Fastfood",
  },
  {
    id: "starbucks",
    logo: "starbucks.svg",
    name: "Starbucks",
    desc: "Coffee",
  },
  {
    id: "coca-cola",
    logo: "coca-cola.svg",
    name: "Coca-Cola",
    desc: "Beverage",
  },
  {
    id: "crocs",
    logo: "crocs.svg",
    name: "Crocs",
    desc: "Shoes",
  },
  {
    id: "berkshire-hathaway",
    logo: "berkshire-hathaway.svg",
    name: "Berkshire Hathaway",
    desc: "Investments",
  },
  {
    id: "costco",
    logo: "costco.svg",
    name: "Costco Wholesale",
    desc: "Discount Store",
  },
  {
    id: "eli-lilly",
    logo: "eli-lilly.svg",
    name: "Eli Lilly",
    desc: "pharmaceuticals",
  },
  {
    id: "novo-nordisk",
    logo: "logo.svg",
    name: "Novo NOrdisk",
    desc: "pharmaceuticals, diabetes, diet",
  },
  {
    id: "amazon",
    logo: "amazon.svg",
    name: "Amazon.com",
    desc: "e-commerce, AWS",
  },
  {
    id: "nvidia",
    logo: "nvidia.svg",
    name: "NVIDIA",
    desc: "graphics card, GPU",
  },
  {
    id: "tesla",
    logo: "tesla.svg",
    name: "Tesla",
    desc: "electric vehicles, renewable energy, AI",
  },
  {
    id: "meta",
    logo: "meta.svg",
    name: "Meta",
    desc: "Facebook, Instagram",
  },
  {
    id: "exxon-mobil",
    logo: "exxon-mobil.svg",
    name: "ExxonMobil",
    desc: "oil, gas",
  },
  {
    id: "unitedhealth",
    logo: "unitedhealth.svg",
    name: "UnitedHealth Group",
    desc: "healthcare, health insurance",
  },
  {
    id: "jp-morgan",
    logo: "jp-morgan.png",
    name: "J.P.Moragn",
    desc: "banking, financial services",
  },
  {
    id: "visa",
    logo: "visa.png",
    name: "Visa",
    desc: "payment, card",
  },
  {
    id: "procter-and-gamble",
    logo: "procter-and-gamble.svg",
    name: "P&G (Procter & Gamble)",
    desc: "household goods, consumer goods",
  },
  {
    id: "broadcom",
    logo: "broadcom.svg",
    name: "Broadcom",
    desc: "semiconductor",
  },
  {
    id: "mastercard",
    logo: "mastercard.svg",
    name: "Mastercard",
    desc: "payment, card",
  },
  {
    id: "home-depot",
    logo: "home-depot.svg",
    name: "Home Depot",
    desc: "interior",
  },
  {
    id: "chevron",
    logo: "chevron.svg",
    name: "Chevron",
    desc: "oil, natural gas",
  },
  {
    id: "abbvie",
    logo: "abbvie.svg",
    name: "AbbVie",
    desc: "Biopharmaceutical",
  },
  {
    id: "advanced-micro-devices",
    logo: "advanced-micro-devices.svg",
    name: "AMD (Advanced Micro Devices)",
    desc: "Semiconductor, CPU, GPU",
  },
  {
    id: "pepsico",
    logo: "pepsico.svg",
    name: "PepsiCo",
    desc: "Pepsi, drinks, snacks",
  },
  {
    id: "netflix",
    logo: "netflix.png",
    name: "Netflix",
    desc: "Streaming, movies, dramas",
  },
  {
    id: "cisco",
    logo: "cisco.svg",
    name: "Cisco Systems",
    desc: "communication equipment",
  },
  {
    id: "t-mobile-us",
    logo: "t-mobile-us.svg",
    name: "T-Mobile US",
    desc: "American wireless carrier",
  },
  {
    id: "intuit",
    logo: "intuit.svg",
    name: "Intuit",
    desc: "financial management software",
  },
  {
    id: "comcast",
    logo: "comcast.svg",
    name: "Comcast",
    desc: "TV broadcast, Internet",
  },
  {
    id: "amgen",
    logo: "amgen.svg",
    name: "Amgen",
    desc: "Biopharmaceuticals",
  },
  {
    id: "texas-instruments",
    logo: "texas-instruments.svg",
    name: "Texas Instruments",
    desc: "semiconductor",
  },
  {
    id: "salesforce",
    logo: "salesforce.svg",
    name: "Salesforce",
    desc: "Customer Management, CRM",
  },
  {
    id: "accenture",
    logo: "accenture.svg",
    name: "Accenture",
    desc: "Consulting, IT",
  },
  {
    id: "merck",
    logo: "merck.svg",
    name: "Merck",
    desc: "Pharmaceuticals, life sciences",
  },
  {
    id: "bank-of-america",
    logo: "bank-of-america.svg",
    name: "Bank of America",
    desc: "financial services, banking",
  },
  {
    id: "united-parcel-service",
    logo: "united-parcel-service.svg",
    name: "UPS (United Parcel Service)",
    desc: "Logistics, delivery",
  },
  {
    id: "verizon",
    logo: "verizon.svg",
    name: "Verizon",
    desc: "American wireless carrier",
  },
  {
    id: "pfizer",
    logo: "pfizer.svg",
    name: "Pfizer",
    desc: "Pharmaceutical, vaccine",
  },
  {
    id: "blackrock",
    logo: "blackrock.svg",
    name: "BlackRock",
    desc: "asset management, investment products",
  },
  {
    id: "lockheed-martin",
    logo: "lockheed-martin.svg",
    name: "Lockheed Martin",
    desc: "defense, aerospace, fighter aircraft",
  },
  {
    id: "automatic-data-processing",
    logo: "automatic-data-processing.svg",
    name: "ADP (Automatic Data Processing)",
    desc: "Human Resources Management Software",
  },
  {
    id: "blackstone",
    logo: "blackstone.svg",
    name: "Blackstone",
    desc: "Investment Management",
  },
  {
    id: "altria-group",
    logo: "altria-group.svg",
    name: "Altria Group",
    desc: "cigarette",
  },
  {
    id: "illinois-tool-works",
    logo: "illinois-tool.svg",
    name: "Illinois Tool Works",
    desc: "industrial equipment",
  },
  {
    id: "eog-resources",
    logo: "eog-resources.svg",
    name: "EOG Resources",
    desc: "Shale oil and gas",
  },
];
