import { AssetListItem, AssetType } from "./model";

export const krStocks: AssetListItem[] = [
  {
    id: "alphabet-class-a",
    logo: "alphabet-class-a.svg",
    name: "구글 알파벳 (Google Alphabet)",
    desc: "IT, 검색",
  },
  {
    id: "apple",
    logo: "apple.svg",
    name: "애플 (Apple)",
    desc: "IT, 아이폰",
  },
  {
    id: "microsoft",
    logo: "microsoft.svg",
    name: "마이크로소프트 (Microsoft)",
    desc: "IT, ChatGPT",
  },
  {
    id: "adobe",
    logo: "adobe.svg",
    name: "어도비 (Adobe)",
    desc: "콘텐츠 제작 소프트웨어",
  },
  {
    id: "johnson-and-johnson",
    logo: "johnson-and-johnson.svg",
    name: "존슨앤존슨 (Johnson & Johnson)",
    desc: "미국 의료",
  },
  {
    id: "nike",
    logo: "nike.svg",
    name: "나이키 (Nike)",
    desc: "운동화, 스포츠 용품",
  },
  {
    id: "3m",
    logo: "3m.png",
    name: "3M",
    desc: "과학",
  },
  {
    id: "logitech",
    logo: "logitech.svg",
    name: "로지텍 (Logitech)",
    desc: "PC 주변기기",
  },
  {
    id: "mcdonalds",
    logo: "mcdonalds.svg",
    name: "맥도날드 (Mcdonald's)",
    desc: "패스트푸드",
  },
  {
    id: "starbucks",
    logo: "starbucks.svg",
    name: "스타벅스 (Starbucks)",
    desc: "커피",
  },
  {
    id: "coca-cola",
    logo: "coca-cola.svg",
    name: "코카콜라 (Coca-Cola)",
    desc: "음료",
  },
  {
    id: "crocs",
    logo: "crocs.svg",
    name: "크록스 (Crocs)",
    desc: "신발",
  },
  {
    id: "berkshire-hathaway",
    logo: "berkshire-hathaway.svg",
    name: "버크셔 해서웨이 (Berkshire Hathaway)",
    desc: "투자",
  },
  {
    id: "costco",
    logo: "costco.svg",
    name: "코스트코 (Costco)",
    desc: "창고형 할인점",
  },
  {
    id: "eli-lilly",
    logo: "eli-lilly.svg",
    name: "일라이릴리 (Eli Lilly)",
    desc: "제약",
  },
  {
    id: "novo-nordisk",
    logo: "logo.svg",
    name: "노보 노디스크 (Novo Nordisk)",
    desc: "제약, 당뇨, 다이어트",
  },
  {
    id: "amazon",
    logo: "amazon.svg",
    name: "아마존 (Amazon.com)",
    desc: "전자상거래, AWS",
  },
  {
    id: "nvidia",
    logo: "nvidia.svg",
    name: "엔비디아 (NVIDIA)",
    desc: "그래픽카드, GPU",
  },
  {
    id: "tesla",
    logo: "tesla.svg",
    name: "테슬라 (Tesla)",
    desc: "전기 자동차, 재생 에너지, AI",
  },
  {
    id: "meta",
    logo: "meta.svg",
    name: "메타 (Meta)",
    desc: "페이스북, 인스타그램",
  },
  {
    id: "exxon-mobil",
    logo: "exxon-mobil.svg",
    name: "엑슨모빌 (ExxonMobil)",
    desc: "석유, 가스",
  },
  {
    id: "unitedhealth",
    logo: "unitedhealth.svg",
    name: "유나이티드헬스그룹 (UnitedHealth Group)",
    desc: "헬스케어, 건강보험",
  },
  {
    id: "jp-morgan",
    logo: "jp-morgan.png",
    name: "JP모건 (J.P.Moragn)",
    desc: "은행, 금융 서비스",
  },
  {
    id: "visa",
    logo: "visa.png",
    name: "비자 (Visa)",
    desc: "결제, 카드",
  },
  {
    id: "procter-and-gamble",
    logo: "procter-and-gamble.svg",
    name: "P&G (Procter & Gamble)",
    desc: "생활 용품, 소비재",
  },
  {
    id: "broadcom",
    logo: "broadcom.svg",
    name: "브로드컴 (Broadcom)",
    desc: "반도체",
  },
  {
    id: "mastercard",
    logo: "mastercard.svg",
    name: "마스터카드 (Mastercard)",
    desc: "결제, 카드",
  },
  {
    id: "home-depot",
    logo: "home-depot.svg",
    name: "홈디포 (Home Depot)",
    desc: "인테리어",
  },
  {
    id: "chevron",
    logo: "chevron.svg",
    name: "셰브론 (Chevron)",
    desc: "석유, 천연가스",
  },
  {
    id: "abbvie",
    logo: "abbvie.svg",
    name: "애브비 (AbbVie)",
    desc: "바이오제약",
  },
  {
    id: "advanced-micro-devices",
    logo: "advanced-micro-devices.svg",
    name: "AMD (Advanced Micro Devices)",
    desc: "반도체, CPU, GPU",
  },
  {
    id: "pepsico",
    logo: "pepsico.svg",
    name: "펩시코 (PepsiCo)",
    desc: "펩시, 음료, 스낵",
  },
  {
    id: "netflix",
    logo: "netflix.png",
    name: "넷플릭스 (Netflix)",
    desc: "스트리밍, 영화, 드라마",
  },
  {
    id: "cisco",
    logo: "cisco.svg",
    name: "시스코 (Cisco Systems)",
    desc: "통신 장비",
  },
  {
    id: "intel",
    logo: "intel.png",
    name: "인텔 (Intel)",
    desc: "반도체, CPU",
  },
  {
    id: "t-mobile-us",
    logo: "t-mobile-us.svg",
    name: "T-Mobile US",
    desc: "미국 통신사",
  },
  {
    id: "intuit",
    logo: "intuit.svg",
    name: "인튜이트 (Intuit)",
    desc: "재무 관리 소프트웨어",
  },
  {
    id: "comcast",
    logo: "comcast.svg",
    name: "컴캐스트 (Comcast)",
    desc: "TV 방송, 인터넷",
  },
  {
    id: "amgen",
    logo: "amgen.svg",
    name: "암젠 (Amgen)",
    desc: "바이오 의약품",
  },
  {
    id: "texas-instruments",
    logo: "texas-instruments.svg",
    name: "텍사스 인스트루먼트 (Texas Instruments)",
    desc: "반도체",
  },
  {
    id: "salesforce",
    logo: "salesforce.svg",
    name: "세일즈포스 (Salesforce)",
    desc: "고객 관리, CRM",
  },
  {
    id: "accenture",
    logo: "accenture.svg",
    name: "액센츄어 (Accenture)",
    desc: "컨설팅, IT",
  },
  {
    id: "merck",
    logo: "merck.svg",
    name: "머크 (Merck)",
    desc: "제약, 생명과학",
  },
  {
    id: "bank-of-america",
    logo: "bank-of-america.svg",
    name: "뱅크오브아메리카 (Bank of America)",
    desc: "금융 서비스, 은행",
  },
  {
    id: "united-parcel-service",
    logo: "united-parcel-service.svg",
    name: "UPS (United Parcel Service)",
    desc: "물류, 택배",
  },
  {
    id: "verizon",
    logo: "verizon.svg",
    name: "버라이즌 (Verizon)",
    desc: "미국 통신사",
  },
  {
    id: "pfizer",
    logo: "pfizer.svg",
    name: "화이자 (Pfizer)",
    desc: "제약, 백신",
  },
  {
    id: "blackrock",
    logo: "blackrock.svg",
    name: "블랙록 (BlackRock)",
    desc: "자산 관리, 투자 상품",
  },
  {
    id: "lockheed-martin",
    logo: "lockheed-martin.svg",
    name: "록히드 마틴 (Lockheed Martin)",
    desc: "방위, 항공우주, 전투기",
  },
  {
    id: "automatic-data-processing",
    logo: "automatic-data-processing.svg",
    name: "ADP (Automatic Data Processing)",
    desc: "인사 관리 소프트웨어",
  },
  {
    id: "blackstone",
    logo: "blackstone.svg",
    name: "블랙스톤 (Blackstone)",
    desc: "투자 관리",
  },
  {
    id: "altria-group",
    logo: "altria-group.svg",
    name: "알트리아 그룹 (Altria Group)",
    desc: "담배",
  },
  {
    id: "illinois-tool-works",
    logo: "illinois-tool.svg",
    name: "일리노이 툴 웍스 (Illinois Tool Works)",
    desc: "산업 장비",
  },
  {
    id: "eog-resources",
    logo: "eog-resources.svg",
    name: "EOG Resources",
    desc: "셰일 석유 가스",
  },
  {
    id: "arm-holdings",
    logo: "logo.svg",
    name: "Arm Holdings",
    desc: "반도체",
  },
  {
    id: "qualcomm",
    logo: "logo.svg",
    name: "퀄컴 (Qaulcomm)",
    desc: "반도체",
  },
  {
    id: "ibm",
    logo: "logo.svg",
    name: "IBM",
    desc: "IT, 컴퓨터",
  },

  {
    id: "yuhan-yanghang",
    logo: "logo.png",
    name: "유한양행",
    desc: "제약",
  },
  {
    id: "sk-telecom",
    logo: "logo.svg",
    name: "SK텔레콤",
    desc: "통신사",
  },
  {
    id: "naver",
    logo: "logo.svg",
    name: "네이버 (NAVER)",
    desc: "IT, 검색",
  },
  {
    id: "samsung-electronics",
    logo: "logo.svg",
    name: "삼성전자",
    desc: "반도체",
  },
  {
    id: "cj-logistics",
    logo: "logo.svg",
    name: "CJ대한통운",
    desc: "물류, 택배",
  },
  {
    id: "toyota-motor",
    logo: "logo.svg",
    name: "도요타자동차 (Toyota Motor)",
    desc: "자동차",
  },
];
